/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/late_night_office/scene.gltf --transform 
Files: public/late_night_office/scene.gltf [13.72KB] > /Users/tony/Desktop/resume/scene-transformed.glb [2.13MB] (-15423%)
Author: Minh Nguyen (https://sketchfab.com/Minh_Nguyen_2004)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/late-night-office-29986085d4a6477c9dda61e63327bdfc
Title: Late Night Office
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Room_ROOM_Mat_0.geometry} material={materials.ROOM_Mat} position={[-0.191, 1.685, -0.338]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Window_WINDOW_Mat_0.geometry} material={materials.WINDOW_Mat} position={[-0.195, 1.666, -0.28]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Boxes_BOXES_Mat_0.geometry} material={materials.BOXES_Mat} position={[0.1, 1.42, 0.024]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
