/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Cinnamine3D (https://sketchfab.com/LordCinn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pixel-plane-da5c802719844a86b9464f73c633cdd1
Title: PIXEL PLANE
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const AirPlane = (props) =>  {
    const group = useRef()
const { nodes, materials, animations } = useGLTF('pixel_plane/scene.gltf')
const { actions } = useAnimations(animations, group)
return (
    <group ref={group} {...props} dispose={null}>
        <group name="Sketchfab_Scene">
            <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                <group name="851ef2b194494e539ad187404fbe584bfbx" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_2">
                        <group name="RootNode">
                            <group name="Cube000" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                            <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                                <group name="Object_6">
                                    <primitive object={nodes._rootJoint} />
                                    <skinnedMesh
                                        name="Object_9"
                                        geometry={nodes.Object_9.geometry}
                                        material={materials['Material.026']}
                                        skeleton={nodes.Object_9.skeleton}
                                    />
                                    <group name="Object_8" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    </group>
)
}

useGLTF.preload('pixel_plane/scene.gltf')
export default AirPlane
