/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Stan (https://sketchfab.com/Stas_SayHallo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-cat-00ea25ccad8344cbaedc89d70bb75a49
Title: Cartoon Cat
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Cat = (props) => {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('models/cat.glb')
    const { actions } = useAnimations(animations, group)
    useEffect(() => {
        actions['waiting'].play();
    }
    )
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
                    <group name="root">
                        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                            <group name="Armature_53">
                                <group name="GLTF_created_0">
                                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                                    <skinnedMesh
                                        name="Object_7"
                                        geometry={nodes.Object_7.geometry}
                                        material={materials['red.001']}
                                        skeleton={nodes.Object_7.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_9"
                                        geometry={nodes.Object_9.geometry}
                                        material={materials.material}
                                        skeleton={nodes.Object_9.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_11"
                                        geometry={nodes.Object_11.geometry}
                                        material={materials.stroke}
                                        skeleton={nodes.Object_11.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_13"
                                        geometry={nodes.Object_13.geometry}
                                        material={materials.material}
                                        skeleton={nodes.Object_13.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_15"
                                        geometry={nodes.Object_15.geometry}
                                        material={materials.stroke}
                                        skeleton={nodes.Object_15.skeleton}
                                    />
                                    <group name="bow_48" />
                                    <group name="catBody_49" />
                                    <group name="catStroke_50" />
                                    <group name="eye_51" />
                                    <group name="eyeStroke_52" />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('models/cat.glb')
export default Cat