/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: dark_igorek (https://sketchfab.com/dark_igorek)
License: COPYRIGHT TO dark_igorek
Source: https://sketchfab.com/3d-models/lumen-vgs-pack-f1c6f36076154777809b30a2e1c50ba3
Title: Lumen VGS Pack
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const GameConsole = (props) => {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('lumen_vgs_pack/lumen_vgs_pack.glb')
    const { actions } = useAnimations(animations, group)
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="root">
                        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                            <group name="Lumen_Monitor_0" position={[-0.025, 0.263, -3.69]}>
                                <mesh
                                    name="Object_4"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_4.geometry}
                                    material={materials.Monitor_body_mat}
                                />
                                <mesh
                                    name="Object_5"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_5.geometry}
                                    material={materials.Monitor_details_one_mat}
                                />
                                <mesh
                                    name="Object_6"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_6.geometry}
                                    material={materials.Monitor_glass_mat}
                                />
                                <mesh
                                    name="Object_7"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_7.geometry}
                                    material={materials.Monitor_details_two_mat}
                                />
                            </group>
                            <group name="Load_block_item001_1">
                                <mesh
                                    name="Object_9"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_9.geometry}
                                    material={materials.Monitor_screen}
                                />
                            </group>
                            <group name="Load_block_item002_2">
                                <mesh
                                    name="Object_11"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_11.geometry}
                                    material={materials.Monitor_screen}
                                />
                            </group>
                            <group name="Load_block_item003_3">
                                <mesh
                                    name="Object_13"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_13.geometry}
                                    material={materials.Monitor_screen}
                                />
                            </group>
                            <group name="Load_block_item004_4">
                                <mesh
                                    name="Object_15"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_15.geometry}
                                    material={materials.Monitor_screen}
                                />
                            </group>
                            <group name="Load_block_item005_5">
                                <mesh
                                    name="Object_17"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_17.geometry}
                                    material={materials.Monitor_screen}
                                />
                            </group>
                            <group name="Load_block_item006_6">
                                <mesh
                                    name="Object_19"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_19.geometry}
                                    material={materials.Monitor_screen}
                                />
                            </group>
                            <group
                                name="Bricktris_9"
                                position={[0.648, 0.577, 0.245]}
                                rotation={[0, -Math.PI / 2, 0]}>
                                <mesh
                                    name="Object_21"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_21.geometry}
                                    material={materials.Gamepad_and_cartridge}
                                />
                                <mesh
                                    name="Object_22"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_22.geometry}
                                    material={materials.Glass}
                                />
                                <group
                                    name="front_sticker_7"
                                    position={[0.051, 0.15, 0.01]}
                                    rotation={[0, Math.PI / 2, 0]}>
                                    <mesh
                                        name="Object_24"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_24.geometry}
                                        material={materials.Gamepad_and_cartridge}
                                    />
                                </group>
                                <group
                                    name="lent001_8"
                                    position={[0.04, -0.007, -0.035]}
                                    rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
                                    <mesh
                                        name="Object_26"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_26.geometry}
                                        material={materials.Gamepad_and_cartridge}
                                    />
                                </group>
                            </group>
                            <group
                                name="Bricktris_copy_14"
                                position={[-2.52, 0.072, 1.591]}
                                rotation={[0, -0.873, Math.PI]}>
                                <mesh
                                    name="Object_28"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_28.geometry}
                                    material={materials.Gamepad_and_cartridge}
                                />
                                <mesh
                                    name="Object_29"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_29.geometry}
                                    material={materials.Glass}
                                />
                                <group
                                    name="front_sticker002_10"
                                    position={[0.051, 0.15, 0.01]}
                                    rotation={[0, Math.PI / 2, 0]}>
                                    <mesh
                                        name="Object_31"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_31.geometry}
                                        material={materials.Gamepad_and_cartridge}
                                    />
                                </group>
                                <group
                                    name="lent_11"
                                    position={[0.04, -0.007, -0.035]}
                                    rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
                                    <mesh
                                        name="Object_33"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_33.geometry}
                                        material={materials.Gamepad_and_cartridge}
                                    />
                                </group>
                                <group
                                    name="lent_big_12"
                                    position={[0.181, 0.018, 0.142]}
                                    rotation={[0, Math.PI / 2, 0]}>
                                    <mesh
                                        name="Object_35"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_35.geometry}
                                        material={materials.Gamepad_and_cartridge}
                                    />
                                </group>
                                <group
                                    name="lent_small_13"
                                    position={[-0.156, 0.018, -0.145]}
                                    rotation={[0, Math.PI / 2, 0]}>
                                    <mesh
                                        name="Object_37"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_37.geometry}
                                        material={materials.Gamepad_and_cartridge}
                                    />
                                </group>
                            </group>
                            <group
                                name="gamepad_1_15"
                                position={[1.197, 0.058, 2.397]}
                                rotation={[0, Math.PI / 6, 0]}>
                                <mesh
                                    name="Object_39"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_39.geometry}
                                    material={materials.Gamepad_and_cartridge}
                                />
                            </group>
                            <group
                                name="gamepad_2_16"
                                position={[2.119, 0.228, 1.283]}
                                rotation={[1.319, -0.074, 0.281]}>
                                <mesh
                                    name="Object_41"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_41.geometry}
                                    material={materials.Gamepad_and_cartridge}
                                />
                            </group>
                            <group
                                name="Lumen_Video_Game_System_21"
                                position={[-0.382, 1.053, -0.126]}
                                rotation={[0, -Math.PI / 2, 0]}>
                                <mesh
                                    name="Object_43"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_43.geometry}
                                    material={materials.VGS_body_mat}
                                />
                                <mesh
                                    name="Object_44"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_44.geometry}
                                    material={materials.VGS_details_one_mat}
                                />
                                <mesh
                                    name="Object_45"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_45.geometry}
                                    material={materials.Glass}
                                />
                                <mesh
                                    name="Object_46"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_46.geometry}
                                    material={materials.VGS_details_two_mat}
                                />
                                <group
                                    name="Lock_cartridge_17"
                                    position={[-0.194, -0.545, -1.026]}
                                    rotation={[0, Math.PI / 2, 0]}>
                                    <mesh
                                        name="Object_48"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_48.geometry}
                                        material={materials.VGS_details_two_mat}
                                    />
                                </group>
                                <group
                                    name="Reader_18"
                                    position={[0.384, -0.623, -1.026]}
                                    rotation={[0, Math.PI / 2, 0]}>
                                    <mesh
                                        name="Object_50"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_50.geometry}
                                        material={materials.VGS_details_two_mat}
                                    />
                                </group>
                                <group
                                    name="Side_lock_cartridge_20"
                                    position={[0.369, -0.578, -0.559]}
                                    rotation={[0, Math.PI / 2, 0]}>
                                    <mesh
                                        name="Object_52"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_52.geometry}
                                        material={materials.VGS_details_two_mat}
                                    />
                                    <group name="eject_gear_19" position={[0, 0.121, 0]}>
                                        <mesh
                                            name="Object_54"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Object_54.geometry}
                                            material={materials.VGS_details_two_mat}
                                        />
                                    </group>
                                </group>
                            </group>
                            <group
                                name="Super_Lumia_Bros_26"
                                position={[-2.652, 0.458, 0.587]}
                                rotation={[Math.PI, Math.PI / 4, -Math.PI / 2]}>
                                <mesh
                                    name="Object_56"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_56.geometry}
                                    material={materials.Gamepad_and_cartridge}
                                />
                                <mesh
                                    name="Object_57"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_57.geometry}
                                    material={materials.Glass}
                                />
                                <group
                                    name="front_sticker001_22"
                                    position={[0.051, 0.15, 0.01]}
                                    rotation={[0, Math.PI / 2, 0]}>
                                    <mesh
                                        name="Object_59"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_59.geometry}
                                        material={materials.Gamepad_and_cartridge}
                                    />
                                </group>
                                <group
                                    name="lent002_23"
                                    position={[0.04, -0.007, -0.035]}
                                    rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
                                    <mesh
                                        name="Object_61"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_61.geometry}
                                        material={materials.Gamepad_and_cartridge}
                                    />
                                </group>
                                <group
                                    name="lent_big001_24"
                                    position={[0.181, 0.018, 0.142]}
                                    rotation={[0, Math.PI / 2, 0]}>
                                    <mesh
                                        name="Object_63"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_63.geometry}
                                        material={materials.Gamepad_and_cartridge}
                                    />
                                </group>
                                <group
                                    name="lent_small001_25"
                                    position={[-0.156, 0.018, -0.145]}
                                    rotation={[0, Math.PI / 2, 0]}>
                                    <mesh
                                        name="Object_65"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_65.geometry}
                                        material={materials.Gamepad_and_cartridge}
                                    />
                                </group>
                            </group>
                            <group name="fan_27" position={[-0.034, 0.584, -0.661]}>
                                <mesh
                                    name="Object_67"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_67.geometry}
                                    material={materials.VGS_details_two_mat}
                                />
                            </group>
                            <group name="lent_big002_28" position={[0.506, 0.595, 0.425]}>
                                <mesh
                                    name="Object_69"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_69.geometry}
                                    material={materials.Gamepad_and_cartridge}
                                />
                            </group>
                            <group name="lent_small002_29" position={[0.793, 0.595, 0.089]}>
                                <mesh
                                    name="Object_71"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_71.geometry}
                                    material={materials.Gamepad_and_cartridge}
                                />
                            </group>
                            <group name="roller001_30" position={[0.793, 0.529, 0.089]}>
                                <mesh
                                    name="Object_73"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_73.geometry}
                                    material={materials.VGS_details_two_mat}
                                />
                            </group>
                            <group name="roller002_31" position={[0.506, 0.529, 0.425]}>
                                <mesh
                                    name="Object_75"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_75.geometry}
                                    material={materials.VGS_details_two_mat}
                                />
                            </group>
                            <group name="Lumen_logo_32" position={[-0.025, 1.902, -2.765]}>
                                <mesh
                                    name="Object_77"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_77.geometry}
                                    material={materials.Monitor_screen}
                                />
                            </group>
                            <group
                                name="Lumen_TV_35"
                                position={[2.955, 0.156, -2.17]}
                                rotation={[0, Math.PI / 9, 0]}>
                                <mesh
                                    name="Object_79"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_79.geometry}
                                    material={materials.Monitor_details_two_mat}
                                />
                            </group>
                            <group name="Signal_cable_36" position={[-0.726, 0.432, -1.165]}>
                                <mesh
                                    name="Object_81"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_81.geometry}
                                    material={materials.Monitor_details_two_mat}
                                />
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}
useGLTF.preload('/lumen_vgs_pack/lumen_vgs_pack.gltf')

export default GameConsole
